### PR TITLE
Fix: Rpc & query

### PR DESCRIPTION
**Pull request by 0xFanz**
- Change RPC to plexnode may help a bit, because many users using slingshot
- Remove  ethereum ENS to avoid lookup address error
- Suggest remove davatar to reduce request to ethereum mainet for faster canto request. Display avatar but call many request to ethereum are not need for now
- Change pastAuctions query to fetch single item

Addition:
- We could implement like this : https://css-tricks.com/inline-svg-cached to cache svg files. Or just simple generate all neons svg  or https://docs.ipfs.tech/how-to/mint-nfts-with-ipfs/#a-short-introduction-to-nfts

### CODE REVIEW

**Comment by froggiedev** [comment]
@web3-fanz great idea to implement svg caching, or to pre-generate the neons svgs and post to ipfs. either seems sufficient, though ipfs can sometimes be slow.

i am going to merge this PR, because it greatly improves the rpc situation. can you look into the newly introduced bug where I cannot view the previous auction? (it loads forever, then sometimes jumps to 50+ auctions ago)

**Comment by froggiedev** [comment]
@web3-fanz had to revert because it broke the production build. you will need to re-open once the issue has been fixed. make sure to test with `yarn build` and serving the file locally.

**Comment by 0xFanz** [comment]
> @web3-fanz great idea to implement svg caching, or to pre-generate the neons svgs and post to ipfs. either seems sufficient, though ipfs can sometimes be slow.
> 
> i am going to merge this PR, because it greatly improves the rpc situation. can you look into the newly introduced bug where I cannot view the previous auction? (it loads forever, then sometimes jumps to 50+ auctions ago)

weird bug, because i have testing for hours did not see it, already build & serve as well

**Comment by froggiedev** [comment]
> > @web3-fanz great idea to implement svg caching, or to pre-generate the neons svgs and post to ipfs. either seems sufficient, though ipfs can sometimes be slow.
> > i am going to merge this PR, because it greatly improves the rpc situation. can you look into the newly introduced bug where I cannot view the previous auction? (it loads forever, then sometimes jumps to 50+ auctions ago)
> 
> weird bug, because i have testing for hours did not see it, already build & serve as well

got it figured out, it was a local issue on the production server, all fixed now

**Pull request merged**
